---
title: "HW2"
author: "Jiacheng Wu"
date: "10/6/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```

## Problem 1

```{r}
trash_data = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", range = "A2:N408") %>% 
  janitor::clean_names() %>% 
  na.omit() %>% 
  mutate(sports_balls = round(sports_balls))
```

## Read in precipitation from 2018 and 2019
```{r}
preci18_data = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = "2018 Precipitation", 
             range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2018)          
```

```{r}
preci19_data = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = "2019 Precipitation", 
             range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2019)          
```
 
## Combine rows

```{r}
preci_data = 
  bind_rows(preci18_data, preci19_data) %>% 
  janitor::clean_names() %>% 
  mutate(month = month.name[month]) 
```

  



